In [1]:
import pylab as pl
import numpy as np
import pandas 
import gradientDescent as gd
import loadParametersP1 as params

# 1. Implement a basic gradient descent procedure to minimize scalar functions of a vector argument.
Write it generically, so that you can easily specify the objective function and the function
to compute the gradient. You should be able to specify the initial guess, the step size (or learning
rate) and the convergence criterion (e.g., a threshold such that the algorithm terminates
when the difference in objective function value on two successive steps is below this threshold
or when the norm of the gradient is below this threshold). For this question, you can use a
fixed step size in your implementation. Test your gradient descent procedure on two functions
with the parameters provided by us in parametersp1.txt (for data files, we also provide basic
reading scripts for MATLAB and Python): the negative of a Gaussian function and a quadratic
bowl. Discuss (and illustrate) the effect of the choice of starting guess, the step size, and the
convergence criterion on the resulting solution, as well as how the norm of the gradient evolves
through the iteration.

Things to Do:

1. Test gradient descent procedure on the given functions and parameteres

2. Study the effect of the choice of
    1. starting guess
    2. step size
    3. convergence criteria
3. Study how the norm of the gradient evolves

In [2]:
# Load parameters
gaussMean,gaussCov,quadBowlA,quadBowlb = params.getData()

# Test implementation of gradient descent on Gaussian

objective_fn = lambda x : gd.computeGaussian(x, gaussMean, gaussCov)
gradient_fn = lambda x: gd.differentiateGaussian(x, gaussMean, gaussCov)
                                                                                            
def testImplementation():
    return None 


best_guess, best_value, guess_evolution, fxn_evolution, norm_evolution = gd.gradientDescent(objective_fn,
                                                                                            gradient_fn,
                                                                                            initial_guess= [np.random.randint(0,100),np.random.randint(0,100)], 
                                                                                            step_size=0.01,
                                                                                            convergence = 1e-04)

print best_guess

gaussian deriv:  gaussian:  1.96348219951e-05
[[  1.41415671e-06   0.00000000e+00]
 [  0.00000000e+00   2.02506778e-06]]
gaussian:  1.96348219951e-05
gaussian deriv:  gaussian:  1.96348219951e-05
[[  1.41415671e-06   0.00000000e+00]
 [  0.00000000e+00   2.02506778e-06]]
gaussian:  1.96348219951e-05
objective fun gaussian:  [[  6.09399965e-06   3.07935306e-05]
 [  3.07935306e-05   6.32632520e-05]]
[[  2.61880873e-05   1.12539540e-04]
 [  1.12539540e-04   8.43778244e-05]]
gaussian:  [[  6.09399965e-06   3.07935306e-05]
 [  3.07935306e-05   6.32632520e-05]]
gaussian:  1.96348219951e-05


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [ ]:
print fxn_evolution
print norm_evolution

# Plot how the norm changes over time 

# Plot how the function changes over time